package kelompok1_tugasbesar_sistemklinik;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Muhammad Rizki A. S. , Rianda Khusuma, Dista Nurdiana
 */
public class MainFrame extends javax.swing.JFrame  {
    Klinik klinik = new Klinik();
    Conn conn;  
    DefaultListModel<String> listPasien = new DefaultListModel<>();
    Pendaftaran pendaftaran =  new Pendaftaran();
    Resep resep = new Resep();
    Bill bill = new Bill();
    
    
    Pasien pasien = new Pasien();
    Dokter dokter = new Dokter();
    Apoteker apoteker = new Apoteker();
    Resepsionis resepsionis = new Resepsionis();
    LocalDate date = LocalDate.now();
    
    public MainFrame() {
        initComponents();
        conn = new Conn();
        
    }
    public void mainFrameOn(){
        this.setVisible(true);
    }
    public void tambahDaftar(){        
        listPasien.clear();
        try{
            String sql = "SELECT * FROM pasien";
            ResultSet rs = conn.getData(sql);
            while(rs.next()){
                String objek = rs.getString(1);
                listPasien.addElement(objek);
                
            }
            ListDaftarPasien.setModel(listPasien);
            LPKlinik.setText(klinik.getNamaKlinik());
            BCheckUp.setEnabled(false);
            BLihatBill.setEnabled(false);
            BLihatResep.setEnabled(false);
            BDelete.setEnabled(false);
        } catch (SQLException ex) {
            System.err.print(ex);
        }
    }
    public void deleteDaftar(){
        int app;
        if ((app = JOptionPane.showConfirmDialog(null, "Hapus "
                + ListDaftarPasien.getSelectedValue()+ " ?", "", JOptionPane.YES_NO_OPTION)) == 0){
            try {
                String sql = "DELETE FROM pasien WHERE"
                + " nama = '" + ListDaftarPasien.getSelectedValue()+ "'";
                conn.query(sql);
                JOptionPane.showMessageDialog(null, "Successfully Deleted");
                tambahDaftar();
            }catch (Exception ex) {
                System.err.print(ex.getMessage());
            }
        } 
    }
    public String searchNamePasien(){
        try{            
            String sql = "SELECT * FROM pasien WHERE Nama = '"+ 
                    (ListDaftarPasien.getSelectedValue()) +"'";
            ResultSet rs = conn.getData(sql);
            String nama = null;
            while(rs.next()){
                 nama = rs.getString("Nama");
            }
            return nama;
            
        } catch (SQLException ex) {
            System.err.print(ex);            
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListDaftarPasien = new javax.swing.JList<>();
        LPDaftarPasien = new javax.swing.JLabel();
        LPDataPasien = new javax.swing.JLabel();
        LPKlinik = new javax.swing.JLabel();
        BDaftar = new javax.swing.JButton();
        LPNama = new javax.swing.JLabel();
        LNama = new javax.swing.JLabel();
        LPDokter = new javax.swing.JLabel();
        LPTanggal = new javax.swing.JLabel();
        LDokter = new javax.swing.JLabel();
        LTanggal = new javax.swing.JLabel();
        BLihatResep = new javax.swing.JButton();
        BLihatBill = new javax.swing.JButton();
        BDelete = new javax.swing.JButton();
        BCheckUp = new javax.swing.JButton();
        LPPenyakit = new javax.swing.JLabel();
        LPenyakit = new javax.swing.JLabel();
        LJamKerja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListDaftarPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListDaftarPasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListDaftarPasien);

        LPDaftarPasien.setText("Daftar Pasien");

        LPDataPasien.setText("Data Pasien");

        LPKlinik.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LPKlinik.setText("KLINIK SEHAT SEJAHTERA");

        BDaftar.setText("Daftar");
        BDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDaftarActionPerformed(evt);
            }
        });

        BLihatResep.setText("Lihat Resep");
        BLihatResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLihatResepActionPerformed(evt);
            }
        });

        BLihatBill.setText("Lihat Bill");
        BLihatBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLihatBillActionPerformed(evt);
            }
        });

        BDelete.setText("Delete");
        BDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeleteActionPerformed(evt);
            }
        });

        BCheckUp.setText("Check Up");
        BCheckUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCheckUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(LPDaftarPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LPDataPasien)
                .addGap(147, 147, 147))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LPDokter)
                            .addComponent(LPNama)
                            .addComponent(LPPenyakit)
                            .addComponent(LPTanggal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(LPKlinik)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LTanggal)
                    .addComponent(LNama)
                    .addComponent(LDokter)
                    .addComponent(LPenyakit)
                    .addComponent(LJamKerja))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(BDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BLihatResep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCheckUp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BLihatBill, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LPKlinik)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPDaftarPasien)
                    .addComponent(LPDataPasien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LPNama)
                            .addComponent(LNama))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LPDokter)
                            .addComponent(LDokter))
                        .addGap(15, 15, 15)
                        .addComponent(LJamKerja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LPTanggal)
                            .addComponent(LTanggal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LPPenyakit)
                            .addComponent(LPenyakit))
                        .addGap(63, 63, 63)
                        .addComponent(BCheckUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BLihatResep)
                        .addGap(18, 18, 18)
                        .addComponent(BLihatBill))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BDelete)
                    .addComponent(BDaftar))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDaftarActionPerformed
        // TODO add your handling code here:
        resepsionis.pendaftaranPasien(pendaftaran);
        this.setVisible(false);
        //this.dispose();
        
    }//GEN-LAST:event_BDaftarActionPerformed

    private void BLihatResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLihatResepActionPerformed
        String nama = ListDaftarPasien.getSelectedValue();
        String penyakit = dokter.diagnosa(dokter.getHasilCheck());
        String keluhan = null;
        try{            
            String sql = "SELECT * FROM pasien WHERE Nama = '"+ 
                    (ListDaftarPasien.getSelectedValue()) +"'";
            ResultSet rs = conn.getData(sql);
            while(rs.next()){
                 keluhan = rs.getString("Keluhan");
            }
        }catch (SQLException ex) {
            System.err.print(ex);            
        }
        ArrayList resepObat = dokter.buatResep(dokter.getHasilDiagnosa());
        System.out.println(resepObat);        
        resep.setVisible(true);
        resep.pack();
        resep.setLocationRelativeTo(null);
        resep.setDefaultCloseOperation(resep.HIDE_ON_CLOSE);
        resep.tambahDaftar(nama,keluhan,penyakit,resepObat);
    }//GEN-LAST:event_BLihatResepActionPerformed

    private void BDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeleteActionPerformed
        deleteDaftar();
    }//GEN-LAST:event_BDeleteActionPerformed

    private void ListDaftarPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListDaftarPasienMouseClicked
        BLihatBill.setEnabled(false);
        BLihatResep.setEnabled(false);
        LPPenyakit.setText("");    
        LPenyakit.setText("");
        LPNama.setText("Nama      :");
        LPDokter.setText("Dokter     :");
        LPTanggal.setText("Tanggal  :");
        try {
            LDokter.setText(resepsionis.cariDokter(dokter, conn));          
            LJamKerja.setText(dokter.jamKerja(LDokter.getText(), conn));
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        resepsionis.setTanggal(date.toString());
        
        LTanggal.setText(resepsionis.getTanggal());
        LNama.setText(searchNamePasien());
        pasien.setNama(ListDaftarPasien.getSelectedValue());
        BCheckUp.setEnabled(true);
        BDelete.setEnabled(true);
    }//GEN-LAST:event_ListDaftarPasienMouseClicked

    private void BCheckUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCheckUpActionPerformed
        try {
            dokter.checkPasien(pasien, ListDaftarPasien.getSelectedValue(), conn);                       
            LPenyakit.setText(dokter.diagnosa(dokter.getHasilCheck()));
            LPPenyakit.setText("Penyakit :");
            BLihatBill.setEnabled(true);
            BLihatResep.setEnabled(true);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_BCheckUpActionPerformed

    private void BLihatBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLihatBillActionPerformed
        resepsionis.buatBill(pasien, dokter, apoteker, bill);
    }//GEN-LAST:event_BLihatBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCheckUp;
    private javax.swing.JButton BDaftar;
    private javax.swing.JButton BDelete;
    private javax.swing.JButton BLihatBill;
    private javax.swing.JButton BLihatResep;
    private javax.swing.JLabel LDokter;
    private javax.swing.JLabel LJamKerja;
    private javax.swing.JLabel LNama;
    private javax.swing.JLabel LPDaftarPasien;
    private javax.swing.JLabel LPDataPasien;
    private javax.swing.JLabel LPDokter;
    private javax.swing.JLabel LPKlinik;
    private javax.swing.JLabel LPNama;
    private javax.swing.JLabel LPPenyakit;
    private javax.swing.JLabel LPTanggal;
    private javax.swing.JLabel LPenyakit;
    private javax.swing.JLabel LTanggal;
    private javax.swing.JList<String> ListDaftarPasien;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
