package kelompok1_tugasbesar_sistemklinik;

import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Rizki A. S. , Rianda Khusuma, Dista Nurdiana
 */
public class Pendaftaran extends javax.swing.JFrame {
    Conn conn;    
    
    public Pendaftaran() {
        initComponents();
        conn = new Conn();
        
    }
    public LocalDate getTanggalLahir(){
        LocalDate born = LocalDate.of(
            Integer.parseInt(CBYear.getSelectedItem().toString()), 
            CBMonth.getSelectedIndex()+1, 
            Integer.parseInt(CBDay.getSelectedItem().toString())
        );
        return born;
    }
    public String getRBJenisKelamin(){
        if(RBPerempuan.isSelected()) {
            return "Perempuan";
        }else return "Laki-Laki";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        TFNama = new javax.swing.JTextField();
        FPPasien = new javax.swing.JLabel();
        LNama = new javax.swing.JLabel();
        LJenisKelamin = new javax.swing.JLabel();
        LTglLahir = new javax.swing.JLabel();
        LAlamat = new javax.swing.JLabel();
        LRiwayatKesehatan = new javax.swing.JLabel();
        LBiodata = new javax.swing.JLabel();
        LKeluhan = new javax.swing.JLabel();
        LNoHP = new javax.swing.JLabel();
        TFAlamat = new javax.swing.JTextField();
        TFNoHP = new javax.swing.JTextField();
        LRiwayatPenyakit = new javax.swing.JLabel();
        TFKeluhan = new javax.swing.JTextField();
        TFRiwayatPenyakit = new javax.swing.JTextField();
        BSubmitForm = new javax.swing.JButton();
        LSuhuTubuh = new javax.swing.JLabel();
        LTekananDarah = new javax.swing.JLabel();
        TFTekananDarah = new javax.swing.JTextField();
        TFSuhuTubuh = new javax.swing.JTextField();
        CBDay = new javax.swing.JComboBox<>();
        CBMonth = new javax.swing.JComboBox<>();
        CBYear = new javax.swing.JComboBox<>();
        RBPerempuan = new javax.swing.JRadioButton();
        RBLakilaki = new javax.swing.JRadioButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TFNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamaActionPerformed(evt);
            }
        });

        FPPasien.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        FPPasien.setText("FORM PENDAFTARAN PASIEN ");

        LNama.setText("Nama");

        LJenisKelamin.setText("Jenis Kelamin");

        LTglLahir.setText("Tanggal Lahir");

        LAlamat.setText("Alamat");

        LRiwayatKesehatan.setText("RIWAYAT KESEHATAN");

        LBiodata.setText("BIODATA PASIEN");

        LKeluhan.setText("Keluhan");

        LNoHP.setText("Nomor Hp.");

        LRiwayatPenyakit.setText("Riwayat Penyakit");

        BSubmitForm.setText("Submit Form");
        BSubmitForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSubmitFormActionPerformed(evt);
            }
        });

        LSuhuTubuh.setText("Suhu Tubuh");

        LTekananDarah.setText("Tekanan Darah");

        CBDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        CBMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des", " " }));

        CBYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));

        RBPerempuan.setText("Perempuan");

        RBLakilaki.setText("Laki-Laki");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(FPPasien)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(BSubmitForm, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LNama)
                                        .addComponent(LAlamat)
                                        .addComponent(LTglLahir)
                                        .addComponent(LJenisKelamin)
                                        .addComponent(LNoHP))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LBiodata)
                                        .addGap(1, 1, 1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFNama, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(TFAlamat)
                                    .addComponent(TFNoHP)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CBDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(CBMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CBYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RBPerempuan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RBLakilaki))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LRiwayatKesehatan)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LSuhuTubuh)
                                    .addComponent(LTekananDarah))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFSuhuTubuh)
                                    .addComponent(TFTekananDarah)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LKeluhan)
                                    .addComponent(LRiwayatPenyakit))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFKeluhan)
                                    .addComponent(TFRiwayatPenyakit))))))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FPPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LBiodata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LJenisKelamin)
                    .addComponent(RBPerempuan)
                    .addComponent(RBLakilaki))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LTglLahir)
                    .addComponent(CBDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LAlamat)
                    .addComponent(TFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LNoHP)
                    .addComponent(TFNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LRiwayatKesehatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LKeluhan)
                            .addComponent(TFKeluhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LRiwayatPenyakit)
                            .addComponent(TFRiwayatPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFSuhuTubuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LSuhuTubuh))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TFTekananDarah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LTekananDarah)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(BSubmitForm))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamaActionPerformed

    private void BSubmitFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSubmitFormActionPerformed
        
        
        try {
                String sql = "INSERT INTO pasien (Nama,Jenis_Kelamin,Tanggal_Lahir,Alamat,Nomor_HP,Keluhan,Riwayat_Penyakit,Suhu_Tubuh,Tekanan_Darah)"
                    + "VALUES ("
                    + "'" + TFNama.getText() + "',"
                    + "'" + getRBJenisKelamin() + "',"
                    + "'" + getTanggalLahir() + "',"
                    + "'" + TFAlamat.getText() + "',"
                    + "'" + TFNoHP.getText() + "',"
                    + "'" + TFKeluhan.getText() + "',"
                    + "'" + TFRiwayatPenyakit.getText() + "',"
                    + "'" + Integer.parseInt(TFSuhuTubuh.getText()) + "',"
                    + "'" + Integer.parseInt(TFTekananDarah.getText()) + "'"
                    + ");";
                conn.query(sql);
                JOptionPane.showMessageDialog(null,  "Berhasil Disimpan");
        } catch (Exception e) {
                    System.err.println(e.getMessage());
        }
        
        
        //pindah frame ke main frame
        MainFrame mf = new MainFrame();
        mf.mainFrameOn();
        mf.tambahDaftar();
        this.dispose();
    }//GEN-LAST:event_BSubmitFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pendaftaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSubmitForm;
    private javax.swing.JComboBox<String> CBDay;
    private javax.swing.JComboBox<String> CBMonth;
    private javax.swing.JComboBox<String> CBYear;
    private javax.swing.JLabel FPPasien;
    private javax.swing.JLabel LAlamat;
    private javax.swing.JLabel LBiodata;
    private javax.swing.JLabel LJenisKelamin;
    private javax.swing.JLabel LKeluhan;
    private javax.swing.JLabel LNama;
    private javax.swing.JLabel LNoHP;
    private javax.swing.JLabel LRiwayatKesehatan;
    private javax.swing.JLabel LRiwayatPenyakit;
    private javax.swing.JLabel LSuhuTubuh;
    private javax.swing.JLabel LTekananDarah;
    private javax.swing.JLabel LTglLahir;
    private javax.swing.JRadioButton RBLakilaki;
    private javax.swing.JRadioButton RBPerempuan;
    private javax.swing.JTextField TFAlamat;
    private javax.swing.JTextField TFKeluhan;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFNoHP;
    private javax.swing.JTextField TFRiwayatPenyakit;
    private javax.swing.JTextField TFSuhuTubuh;
    private javax.swing.JTextField TFTekananDarah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
